CREATE TABLE SEQ_ADVISORY_YHT
(
);
CREATE TABLE SEQ_CALLIN_YHT
(
);
CREATE TABLE SEQ_CALL_OUT_YHT
(
);
CREATE TABLE SEQ_COMPLAINT_REPLY_YHT
(
);
CREATE TABLE SEQ_COMPLAINT_YHT
(
);
CREATE TABLE SEQ_HOSPITAL_PIPE_YHT
(
);
CREATE TABLE SEQ_KLGMOUDLE_YHT
(
);
CREATE TABLE SEQ_KNOWLEDGEBASE_YHT
(
);
CREATE TABLE SEQ_MENU_YHT
(
);
CREATE TABLE SEQ_REGPEOPLE_YHT
(
);
CREATE TABLE SEQ_REG_ORDER_YHT
(
);
CREATE TABLE SEQ_REG_PIPELINED_YHT
(
);
CREATE TABLE SEQ_ROLE_YHT
(
);
CREATE TABLE SEQ_SYS_LOG_YHT
(
);
CREATE TABLE SEQ_USER_YHT
(
);
CREATE TABLE SEQ_WORK_SCHEMA_YHT
(
);
CREATE TABLE YHT_ADVISORY
(
    ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    ID_CARD_CODE VARCHAR2(40),
    ADRESS VARCHAR2(100),
    ADVISORY_DESC CLOB NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    E_MAIL VARCHAR2(100),
    LINK_TEL VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(20),
    REMARK VARCHAR2(510),
    SEX NUMBER(10,0),
    STATE NUMBER(10,0),
    CALL_ID NUMBER(19,0),
    LAST_OPEAT_USER NUMBER(10,0),
    KNOW_LEDGE_MOUDLE NUMBER(10,0),
    ISSC NUMBER(10,0),
    SCWX_ID VARCHAR2(40)
);
CREATE TABLE YHT_AREA_REGION
(
    REGION_NO VARCHAR2(30) PRIMARY KEY NOT NULL,
    REGION_NAME VARCHAR2(200) NOT NULL,
    PARENT_ID VARCHAR2(30)
);
CREATE TABLE YHT_BASE_DATA
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    DATA VARCHAR2(30) NOT NULL,
    PARENT NUMBER(10,0)
);
CREATE TABLE YHT_CALL_IN
(
    CALL_IN_ORDER NUMBER(19,0) PRIMARY KEY NOT NULL,
    CALL_IN_PHONE VARCHAR2(30) NOT NULL,
    CALL_IN_TIME TIMESTAMP,
    IS_CONNECT NUMBER(10,0),
    OPEATE_ESQ NUMBER(10,0),
    APPROVING NUMBER(10,0),
    CALL_CODE VARCHAR2(200),
    CONNECT_TIME DATE,
    OFF_TIME DATE,
    RECORDING VARCHAR2(200),
    CALL_TYPE INT DEFAULT 0,
    IS_SEND NUMBER(10,0)
);
CREATE TABLE YHT_CALL_OUT
(
    ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    CALL_TIME TIMESTAMP,
    OFF_TIME DATE,
    OUT_TYPE NUMBER(10,0),
    TO_PHONE VARCHAR2(30) NOT NULL,
    OUT_USER NUMBER(10,0),
    IS_CONNECT NUMBER(10,0),
    CALL_CODE VARCHAR2(200),
    CONNECT_TIME DATE,
    RECORDING VARCHAR2(200)
);
CREATE TABLE YHT_COMPLAINT
(
    ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    ADDRESS VARCHAR2(200),
    COMPLAINT_DESC VARCHAR2(4000),
    CREATE_TIMEEE TIMESTAMP,
    E_MAIL VARCHAR2(100),
    FOR_USER VARCHAR2(510),
    FOR_WORK_NO VARCHAR2(40),
    ID_CARD_CODE VARCHAR2(40),
    MOBILE VARCHAR2(30),
    REMARK VARCHAR2(510),
    SEX NUMBER(10,0),
    STATE NUMBER(10,0),
    TRUE_NAME VARCHAR2(30),
    CALL_IN NUMBER(19,0),
    FOR_DEPART NUMBER(10,0),
    LAST_USER NUMBER(10,0),
    FOR_DOCTOR NUMBER(10,0),
    RETURN_STATE NUMBER(10,0),
    FOR_HOSPITAL VARCHAR2(32),
    COMPLAINT_CODE VARCHAR2(510),
    FOR_DEPARTMENT VARCHAR2(100),
    COMPLAINT_TYPE INT DEFAULT 1,
    UPDATE_TIMEEE TIMESTAMP,
    UPDATE_USER NUMBER(10,0)
);
CREATE TABLE YHT_COMPLAINT_REPLY
(
    RID NUMBER(19,0) PRIMARY KEY NOT NULL,
    REPLY_CONTENT VARCHAR2(4000) NOT NULL,
    RECOVERY_UNIT VARCHAR2(510),
    REPLY_TIME TIMESTAMP,
    SPARE_ONE NUMBER(19,0),
    SPARE_TWO VARCHAR2(510),
    COMPLAINT NUMBER(19,0),
    REPLY_USER NUMBER(10,0) NOT NULL
);
CREATE TABLE YHT_DEPART
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    DEPART_DESC VARCHAR2(510),
    CLINIC_FEE FLOAT(126),
    CREATE_TIME TIMESTAMP,
    DEPART_CODE_NO VARCHAR2(32) NOT NULL,
    DEPART_NAME VARCHAR2(100) NOT NULL,
    FACTORAGE_FEE FLOAT(126),
    IS_KEY_DEPARTMENTS NUMBER(1,0) NOT NULL,
    IS_SPECIALTIES NUMBER(1,0) NOT NULL,
    IS_TOP NUMBER(1,0),
    REGISTRY_FEE FLOAT(126),
    SORT_ORDER NUMBER(10,0),
    SPELL_CODE VARCHAR2(20) NOT NULL,
    HOSPITAL_ID NUMBER(10,0)
);
CREATE TABLE YHT_DEPARTS
(
    DEPART_CODE_NO VARCHAR2(32) PRIMARY KEY NOT NULL,
    DEPART_DESC VARCHAR2(510),
    CLINIC_FEE FLOAT(126),
    CREATE_TIME TIMESTAMP,
    DEPART_NAME VARCHAR2(100) NOT NULL,
    FACTORAGE_FEE FLOAT(126),
    IS_KEY_DEPARTMENTS NUMBER(1,0) NOT NULL,
    IS_SPECIALTIES NUMBER(1,0) NOT NULL,
    IS_TOP NUMBER(1,0),
    REGISTRY_FEE FLOAT(126),
    SORT_ORDER NUMBER(10,0),
    SPELL_CODE VARCHAR2(100),
    HOSPITAL_ID VARCHAR2(32)
);
CREATE TABLE YHT_DEPART_WS
(
    CODE NUMBER(19,0) PRIMARY KEY NOT NULL,
    WORK_DATE DATE,
    DEPART VARCHAR2(32)
);
CREATE TABLE YHT_DOCTOR
(
    FOR_WORK_NO VARCHAR2(40) PRIMARY KEY NOT NULL,
    CREATE_TIME TIMESTAMP,
    DESCRIPTION VARCHAR2(4000),
    DOCTOR_INFO VARCHAR2(2000),
    DOCTOR_RANK VARCHAR2(200),
    INTRODUCE_URL VARCHAR2(400),
    IS_EXPERT NUMBER(1,0),
    NAME VARCHAR2(20) NOT NULL,
    PHOTO RAW(255),
    REMARK VARCHAR2(600),
    DOCTOR_SEX NUMBER(10,0),
    SORT_ORDER NUMBER(10,0),
    SPECIALTY VARCHAR2(1000),
    SPELL_CODE VARCHAR2(100),
    TITLE_ID VARCHAR2(40),
    DEPART_CODE VARCHAR2(32),
    ID NUMBER(10,0),
    DEPART_ID NUMBER(10,0),
    DEPARTCODE VARCHAR2(510),
    DEPART RAW(255),
    DOCTORFORDEPARTNAME VARCHAR2(400)
);
CREATE TABLE YHT_DOCTOR_EXPERT
(
    EXPERTS_FEE FLOAT(126),
    FACTORAGE_FEE FLOAT(126),
    IS_TOP NUMBER(1,0),
    REG_COUNT NUMBER(10,0),
    FOR_WORK_NO VARCHAR2(40) PRIMARY KEY NOT NULL,
    ID NUMBER(10,0),
    REG_MINUTE FLOAT(126)
);
CREATE TABLE YHT_DOCTOR_WS
(
    CODE NUMBER(19,0) PRIMARY KEY NOT NULL,
    WORK_DATE DATE,
    DEPART VARCHAR2(32),
    DOCTOR_EXPERT VARCHAR2(40),
    CLINIC_FEE FLOAT(126),
    EXPERTS_FEE FLOAT(126),
    FACTORAGE_FEE FLOAT(126),
    REGISTRY_FEE FLOAT(126)
);
CREATE TABLE YHT_HOSPITAL_INFO
(
    HOSPITAL_CODE VARCHAR2(32) PRIMARY KEY NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    BUS_LINES VARCHAR2(510),
    CREATE_TIME TIMESTAMP,
    HOSPITAL_DESC VARCHAR2(510),
    HOSPITAL_IMAGE RAW(255),
    HOSPITAL_LEVEL VARCHAR2(200) NOT NULL,
    HOSPITAL_TYPE VARCHAR2(200) NOT NULL,
    IS_TOP NUMBER(1,0) NOT NULL,
    LINK_TEL VARCHAR2(30),
    HOSPITAL_NAME VARCHAR2(100) NOT NULL,
    SORT_ORDER NUMBER(10,0),
    SPELL_CODE VARCHAR2(20) NOT NULL,
    USE_MEDICAL VARCHAR2(400),
    WEB_HOST VARCHAR2(200),
    AREA_REGION VARCHAR2(30),
    ID NUMBER(10,0)
);
CREATE TABLE YHT_HOSPITAL_PIPE
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    END_TIME VARCHAR2(40) NOT NULL,
    LAST_UP_DATE TIMESTAMP,
    START_TIME VARCHAR2(40) NOT NULL,
    STATE NUMBER(10,0),
    WORK_TYPE NUMBER(10,0),
    HOSPITAL VARCHAR2(32)
);
CREATE TABLE YHT_KNOWLEDGE_BASE
(
    ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    ADD_TIME TIMESTAMP,
    QUESTION VARCHAR2(2000),
    LAST_USER NUMBER(10,0),
    MODULE NUMBER(10,0) NOT NULL,
    ASKWER CLOB,
    CODE VARCHAR2(32)
);
CREATE TABLE YHT_KNOWLEDGE_MOUDLE
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    MOUDLE_NAME VARCHAR2(510) NOT NULL,
    ORDER_NO NUMBER(10,0) NOT NULL,
    PARENT NUMBER(10,0),
    MOUDLE_CODE VARCHAR2(32),
    PROVINCIAL_CODE VARCHAR2(32)
);
CREATE TABLE YHT_MENU
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    LINK_URL VARCHAR2(510),
    MENU_NAME VARCHAR2(510),
    PARENT NUMBER(10,0),
    ORDER_CODE NUMBER(10,0),
    STATE NUMBER(10,0)
);
CREATE TABLE YHT_RECORDING
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    CREATE_TIMEER TIMESTAMP,
    RECORD_FILE RAW(255) NOT NULL,
    REMARK VARCHAR2(510),
    TITLE VARCHAR2(200) NOT NULL,
    CALL_IN_ORDER NUMBER(19,0),
    OPEART_USER NUMBER(10,0),
    RECORD_CODE VARCHAR2(200)
);
CREATE TABLE YHT_REG_ORDER
(
    CODE NUMBER(19,0) PRIMARY KEY NOT NULL,
    CHECK_CODE VARCHAR2(12) NOT NULL,
    CREATE_TIMEEE TIMESTAMP,
    END_TIME TIMESTAMP,
    ORDER_DESC VARCHAR2(510),
    QUIT_TIME TIMESTAMP,
    STATE NUMBER(10,0),
    STATE_TIME TIMESTAMP,
    TREAT_ORDER NUMBER(10,0) NOT NULL,
    TREAT_PEOPLE_TYPE NUMBER(10,0),
    UPDATE_TIMEEE TIMESTAMP,
    ZHYL_ID NUMBER(19,0),
    CALL_IN_ORDER NUMBER(19,0),
    OPEATE_ESQ NUMBER(10,0),
    REG_PEOPLE NUMBER(19,0),
    REG_PIPELINED NUMBER(19,0),
    TREAT_PEOPLE NUMBER(19,0),
    CANCLE_ESQ NUMBER(10,0),
    QUIT_TYPE NUMBER(10,0),
    ISSC NUMBER(10,0),
    SCWX_ID VARCHAR2(40),
    IDEALREGISTER_TIME TIMESTAMP,
    CANCLENAME VARCHAR2(30),
    CLINIC_FEE FLOAT(126),
    DEPART_CODE_NO VARCHAR2(32),
    DEPART_NAME VARCHAR2(100),
    DOCTOR_NAME VARCHAR2(40),
    EXPERTS_FEE FLOAT(126),
    FACTORAGE_FEE FLOAT(126),
    FOR_WORK_NO VARCHAR2(40),
    HOSPITAL_CODE VARCHAR2(32),
    HOSPITAL_NAME VARCHAR2(100),
    ID_CARD_CODE VARCHAR2(40),
    MEDICAL_NO VARCHAR2(60),
    MEDICAL_TYPE NUMBER(10,0),
    MOBILE VARCHAR2(30),
    OPEATENAME VARCHAR2(30),
    REGTYPE NUMBER(10,0),
    REGISTRY_FEE FLOAT(126),
    SEX NUMBER(10,0),
    TRUE_NAME VARCHAR2(30),
    WORK_DATE DATE
);
CREATE TABLE YHT_REG_PEOPLE
(
    ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    AGE NUMBER(10,0),
    BREAK_PROMISE_COUNT NUMBER(10,0),
    CANCEL_DATE TIMESTAMP,
    ID_CARD_CODE VARCHAR2(40),
    MEDICAL_NO VARCHAR2(60),
    MEDICAL_TYPE NUMBER(19,0),
    MOBILE VARCHAR2(30),
    SEX NUMBER(10,0),
    TRUE_NAME VARCHAR2(30) NOT NULL,
    LAST_USER NUMBER(10,0),
    QUITBLACKRESULT VARCHAR2(510),
    REMOVE_REASON VARCHAR2(4000),
    ISHMD NUMBER(10,0),
    JCLX NUMBER(10,0),
    NOTQHXZCE NUMBER(10,0),
    THCS NUMBER(10,0),
    THXZCS NUMBER(10,0)
);
CREATE TABLE YHT_REG_PIPELINED
(
    CODE NUMBER(19,0) PRIMARY KEY NOT NULL,
    TAKE_VLIDITY TIMESTAMP,
    INIT_REG NUMBER(10,0),
    MAX_REG NUMBER(10,0),
    SPACING_INT NUMBER(10,0),
    WORK_TYPE NUMBER(10,0),
    WORK_SCHEMA NUMBER(19,0),
    STATE NUMBER(10,0)
);
CREATE TABLE YHT_ROLE
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    ROLE_DESC VARCHAR2(510),
    ROLE_NAME VARCHAR2(510) NOT NULL,
    ADD_TIME DATE
);
CREATE TABLE YHT_ROLE_MENU
(
    ROLE_ID NUMBER(10,0) NOT NULL,
    MENU_ID NUMBER(10,0) NOT NULL
);
CREATE TABLE YHT_SOFT_PHONE
(
    PHONE_NO VARCHAR2(30) PRIMARY KEY NOT NULL,
    IS_CONNECT NUMBER(10,0),
    PASSWORD VARCHAR2(30),
    IS_LOGIN NUMBER(10,0),
    GROUP_NAME VARCHAR2(30)
);
CREATE TABLE YHT_SYS_LOG
(
    ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    CREATE_TIME TIMESTAMP,
    MODULE_TYPE NUMBER(10,0),
    OPEATE_CLASS NUMBER(10,0),
    OPEATER_DESC VARCHAR2(510) NOT NULL,
    OPEATER_USER NUMBER(10,0)
);
CREATE TABLE YHT_USER
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    E_MAIL VARCHAR2(60),
    LAST_UPDATE_TIME TIMESTAMP,
    LOG_ERR_COUNT NUMBER(10,0),
    PASSWORD VARCHAR2(70) NOT NULL,
    REG_DATE TIMESTAMP,
    TEL VARCHAR2(30),
    TRUE_NAME VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(36) NOT NULL,
    ROLE NUMBER(10,0),
    DEPARTMENT NUMBER(10,0),
    SEX NUMBER(10,0),
    IS_USERD NUMBER(10,0),
    SOFT_PHONE VARCHAR2(30)
);
ALTER TABLE YHT_ADVISORY ADD FOREIGN KEY ( CALL_ID ) REFERENCES YHT_CALL_IN ( CALL_IN_ORDER );
ALTER TABLE YHT_ADVISORY ADD FOREIGN KEY ( KNOW_LEDGE_MOUDLE ) REFERENCES YHT_KNOWLEDGE_MOUDLE ( ID );
ALTER TABLE YHT_ADVISORY ADD FOREIGN KEY ( LAST_OPEAT_USER ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_AREA_REGION ADD FOREIGN KEY ( PARENT_ID ) REFERENCES YHT_AREA_REGION ( REGION_NO );
ALTER TABLE YHT_BASE_DATA ADD FOREIGN KEY ( PARENT ) REFERENCES YHT_BASE_DATA ( ID );
CREATE UNIQUE INDEX SYS_C006763 ON YHT_BASE_DATA ( DATA );
ALTER TABLE YHT_CALL_IN ADD FOREIGN KEY ( OPEATE_ESQ ) REFERENCES YHT_USER ( ID );
CREATE UNIQUE INDEX SYS_C006770 ON YHT_CALL_IN ( RECORDING );
ALTER TABLE YHT_CALL_OUT ADD FOREIGN KEY ( OUT_USER ) REFERENCES YHT_USER ( ID );
CREATE UNIQUE INDEX SYS_C006777 ON YHT_CALL_OUT ( CALL_CODE );
CREATE UNIQUE INDEX SYS_C006778 ON YHT_CALL_OUT ( RECORDING );
ALTER TABLE YHT_COMPLAINT ADD FOREIGN KEY ( CALL_IN ) REFERENCES YHT_CALL_IN ( CALL_IN_ORDER );
ALTER TABLE YHT_COMPLAINT ADD FOREIGN KEY ( FOR_HOSPITAL ) REFERENCES YHT_HOSPITAL_INFO ( HOSPITAL_CODE );
ALTER TABLE YHT_COMPLAINT ADD FOREIGN KEY ( LAST_USER ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_COMPLAINT ADD FOREIGN KEY ( UPDATE_USER ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_COMPLAINT_REPLY ADD FOREIGN KEY ( COMPLAINT ) REFERENCES YHT_COMPLAINT ( ID );
ALTER TABLE YHT_COMPLAINT_REPLY ADD FOREIGN KEY ( REPLY_USER ) REFERENCES YHT_USER ( ID );
CREATE UNIQUE INDEX SYS_C006794 ON YHT_DEPART ( DEPART_CODE_NO );
ALTER TABLE YHT_DEPARTS ADD FOREIGN KEY ( HOSPITAL_ID ) REFERENCES YHT_HOSPITAL_INFO ( HOSPITAL_CODE );
ALTER TABLE YHT_DEPART_WS ADD FOREIGN KEY ( DEPART ) REFERENCES YHT_DEPARTS ( DEPART_CODE_NO );
ALTER TABLE YHT_DOCTOR ADD FOREIGN KEY ( DEPART_CODE ) REFERENCES YHT_DEPARTS ( DEPART_CODE_NO );
ALTER TABLE YHT_DOCTOR_EXPERT ADD FOREIGN KEY ( FOR_WORK_NO ) REFERENCES YHT_DOCTOR ( FOR_WORK_NO );
ALTER TABLE YHT_DOCTOR_WS ADD FOREIGN KEY ( DEPART ) REFERENCES YHT_DEPARTS ( DEPART_CODE_NO );
CREATE UNIQUE INDEX SYS_DATE ON YHT_DOCTOR_WS ( WORK_DATE );
ALTER TABLE YHT_HOSPITAL_INFO ADD FOREIGN KEY ( AREA_REGION ) REFERENCES YHT_AREA_REGION ( REGION_NO );
CREATE UNIQUE INDEX SYS_C006819 ON YHT_HOSPITAL_INFO ( HOSPITAL_NAME );
ALTER TABLE YHT_HOSPITAL_PIPE ADD FOREIGN KEY ( HOSPITAL ) REFERENCES YHT_HOSPITAL_INFO ( HOSPITAL_CODE );
ALTER TABLE YHT_KNOWLEDGE_BASE ADD FOREIGN KEY ( MODULE ) REFERENCES YHT_KNOWLEDGE_MOUDLE ( ID );
ALTER TABLE YHT_KNOWLEDGE_BASE ADD FOREIGN KEY ( LAST_USER ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_KNOWLEDGE_MOUDLE ADD FOREIGN KEY ( PARENT ) REFERENCES YHT_KNOWLEDGE_MOUDLE ( ID );
ALTER TABLE YHT_MENU ADD FOREIGN KEY ( PARENT ) REFERENCES YHT_MENU ( ID );
ALTER TABLE YHT_RECORDING ADD FOREIGN KEY ( CALL_IN_ORDER ) REFERENCES YHT_CALL_IN ( CALL_IN_ORDER );
ALTER TABLE YHT_RECORDING ADD FOREIGN KEY ( OPEART_USER ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_REG_ORDER ADD FOREIGN KEY ( CALL_IN_ORDER ) REFERENCES YHT_CALL_IN ( CALL_IN_ORDER );
ALTER TABLE YHT_REG_ORDER ADD FOREIGN KEY ( REG_PEOPLE ) REFERENCES YHT_REG_PEOPLE ( ID );
ALTER TABLE YHT_REG_ORDER ADD FOREIGN KEY ( TREAT_PEOPLE ) REFERENCES YHT_REG_PEOPLE ( ID );
ALTER TABLE YHT_REG_ORDER ADD FOREIGN KEY ( REG_PIPELINED ) REFERENCES YHT_REG_PIPELINED ( CODE );
ALTER TABLE YHT_REG_ORDER ADD FOREIGN KEY ( CANCLE_ESQ ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_REG_ORDER ADD FOREIGN KEY ( OPEATE_ESQ ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_REG_PEOPLE ADD FOREIGN KEY ( LAST_USER ) REFERENCES YHT_USER ( ID );
CREATE UNIQUE INDEX IDX_REG_PEOPLE ON YHT_REG_PEOPLE ( ID_CARD_CODE, MOBILE );
CREATE UNIQUE INDEX SYS_C006851 ON YHT_ROLE ( ROLE_NAME );
ALTER TABLE YHT_ROLE_MENU ADD FOREIGN KEY ( MENU_ID ) REFERENCES YHT_MENU ( ID );
ALTER TABLE YHT_ROLE_MENU ADD FOREIGN KEY ( ROLE_ID ) REFERENCES YHT_ROLE ( ID );
ALTER TABLE YHT_SYS_LOG ADD FOREIGN KEY ( OPEATER_USER ) REFERENCES YHT_USER ( ID );
ALTER TABLE YHT_USER ADD FOREIGN KEY ( ROLE ) REFERENCES YHT_ROLE ( ID );
ALTER TABLE YHT_USER ADD FOREIGN KEY ( SOFT_PHONE ) REFERENCES YHT_SOFT_PHONE ( PHONE_NO );
CREATE UNIQUE INDEX SYS_C006864 ON YHT_USER ( USER_NAME );
