
package szsx.yhtwebservice;

import com.hch.security.Config;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "yhtReg", targetNamespace = "http://yhtWebService.szsx",
        wsdlLocation = "http://172.25.223.76:8080/zhylService/services/yhtReg?wsdl")
public class YhtReg
    extends Service
{

    private final static URL YHTREG_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(YhtReg.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = YhtReg.class.getResource(".");
            url = new URL(baseUrl,
                    Config.getString("zhyl_ws_url")
//                    Config.ZhylWsUrl
                            + "?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '" +
                    Config.getString("zhyl_ws_url") +
//                    Config.ZhylWsUrl +
                    "?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        YHTREG_WSDL_LOCATION = url;
    }

    public YhtReg(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YhtReg() {
        super(YHTREG_WSDL_LOCATION, new QName("http://yhtWebService.szsx", "yhtReg"));
    }

    /**
     * 
     * @return
     *     returns YhtRegPortType
     */
    @WebEndpoint(name = "yhtRegHttpPort")
    public YhtRegPortType getYhtRegHttpPort() {
        return super.getPort(new QName("http://yhtWebService.szsx", "yhtRegHttpPort"), YhtRegPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YhtRegPortType
     */
    @WebEndpoint(name = "yhtRegHttpPort")
    public YhtRegPortType getYhtRegHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://yhtWebService.szsx", "yhtRegHttpPort"), YhtRegPortType.class, features);
    }

}
