
package szsx.provplatwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProvPlatService", targetNamespace = "http://provPlatWebService.szsx", wsdlLocation = "http://172.25.223.73//services/ProvPlatService?wsdl")
public class ProvPlatService
    extends Service
{

    private final static URL PROVPLATSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ProvPlatService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ProvPlatService.class.getResource(".");
            url = new URL(baseUrl, "http://172.25.223.73//services/ProvPlatService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.25.223.73//services/ProvPlatService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROVPLATSERVICE_WSDL_LOCATION = url;
    }

    public ProvPlatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvPlatService() {
        super(PROVPLATSERVICE_WSDL_LOCATION, new QName("http://provPlatWebService.szsx", "ProvPlatService"));
    }

    /**
     * 
     * @return
     *     returns ProvPlatServicePortType
     */
    @WebEndpoint(name = "ProvPlatServiceHttpPort")
    public ProvPlatServicePortType getProvPlatServiceHttpPort() {
        return super.getPort(new QName("http://provPlatWebService.szsx", "ProvPlatServiceHttpPort"), ProvPlatServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvPlatServicePortType
     */
    @WebEndpoint(name = "ProvPlatServiceHttpPort")
    public ProvPlatServicePortType getProvPlatServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://provPlatWebService.szsx", "ProvPlatServiceHttpPort"), ProvPlatServicePortType.class, features);
    }

}
