
package szsx.provplatwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProvPlatServicePortType", targetNamespace = "http://provPlatWebService.szsx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProvPlatServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "getDepartInfo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDepartInfo")
    @ResponseWrapper(localName = "getDepartInfoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDepartInfoResponse")
    public String getDepartInfo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "getDoctorWorkInfo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDoctorWorkInfo")
    @ResponseWrapper(localName = "getDoctorWorkInfoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDoctorWorkInfoResponse")
    public String getDoctorWorkInfo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.CancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.CancelOrderResponse")
    public String cancelOrder(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "getDepartWorkInfo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDepartWorkInfo")
    @ResponseWrapper(localName = "getDepartWorkInfoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDepartWorkInfoResponse")
    public String getDepartWorkInfo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "backRegNo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.BackRegNo")
    @ResponseWrapper(localName = "backRegNoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.BackRegNoResponse")
    public String backRegNo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "uploadRegInfo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.UploadRegInfo")
    @ResponseWrapper(localName = "uploadRegInfoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.UploadRegInfoResponse")
    public String uploadRegInfo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "getHospitalInfo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetHospitalInfo")
    @ResponseWrapper(localName = "getHospitalInfoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetHospitalInfoResponse")
    public String getHospitalInfo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "getDoctorInfo", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDoctorInfo")
    @ResponseWrapper(localName = "getDoctorInfoResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetDoctorInfoResponse")
    public String getDoctorInfo(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "getWorkTime", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetWorkTime")
    @ResponseWrapper(localName = "getWorkTimeResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.GetWorkTimeResponse")
    public String getWorkTime(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://provPlatWebService.szsx")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://provPlatWebService.szsx", className = "szsx.provplatwebservice.CreateOrderResponse")
    public String createOrder(
            @WebParam(name = "in0", targetNamespace = "http://provPlatWebService.szsx")
            String in0);

}
